apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: banking

spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-node-1

      containers:
      - name: backend
        image: abhinay281141/backend:1.0   # <-- apni image ka sahi naam likho
        imagePullPolicy: Always

        ports:
        - containerPort: 8080